### ISSUE TITLE
Smile and Thumbs Up Icons Don't work as well here

### ISSUE THREAD

**Issue by kpennell** [DevelopIntelligenceBoulder/report-angular#1]
In the react react version of this, it seemed like clicking would change little icon on the cards from happy face to thumbs up, etc.  Or maybe I was just using the functionality differently.  Not sure if different or I'm just using differently.

**Comment by kpennell** [comment]
Add One button doesn't seem to work.

**Comment by kamrenz** [comment]
Thanks for the feedback.

The 2 versions should interact in the exact same way. I will fix the bugs
tonight.

On Mon, Jul 13, 2015 at 4:50 PM, Kyle Pennell <notifications@github.com>
wrote:

> Add One button doesn't seem to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DevelopIntelligenceBoulder/report-angular/issues/1#issuecomment-121054906>
> .
>



-- 
"This is not another song about the mountains, except about how hard they
are to move. Have you ever stood before them like a mustard seed who's
waiting for some proof?"
- Andrew Peterson

**Comment by kamrenz** [comment]
Should be fixed

**Comment by kpennell** [comment]
I think my problem is that I'm not totally sure how it's supposed to work.
I'm guessing the icons are supposed to be break even points?

On Wed, Jul 15, 2015 at 2:25 PM, Kamren Zorgdrager <notifications@github.com

**Comment by kamrenz** [comment]
When you load the reports icon-fonts show up if the gross profit is over $200. If the gross profit is under $200 they don't show up. Every time a user clicks the up or down button on the number range to show more/less reports the images are randomly rechosen and updated.
